### ISSUE TITLE
Remove secondary, outdated instruction files

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr#100]
There's a previously used set of instructions directly under the instructions folder but outside of the instructions>labs folder that hosted the previously updated instructions. They are now an outdated duplicate as the current instructions are being kept and maintained under the new folder.

Can we please get the outdated and redundant instructions removed?

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Update the code, waiting for result.

**Comment by stonezy123** [comment]
Now, the repo was synced.
