### ISSUE TITLE
file path issue #90 through #99 recurring again

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr#101]
This commit: https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr/commit/958402abf6c4d8f6a91c2ee58e91d6ada22b6d0b has made the issues #90 through #99 happening again because it changed the location of the Linked_images_Files folder. 

Could you please revert back to the https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr/commit/cd198afd2b0e002ca0cd3f26a8834182515d8cca version?

**Comment by LuongNguyen0906** [comment]
I have fixed the issue. 

thank you!
