### ISSUE TITLE
Every Lab Missing Images

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr#26]
Here is one example of a broken linked image:
(Linked_image_Files/01-prepare-data-with-power-query-in-power-bi-desktop_image1.png)

This repo does not have a Linked_image_Files folder.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by unisong114** [comment]
Hi, I also want the image to be displayed quickly in the lab.

**Comment by stonezy123** [comment]
The image in Loclization status, waiting for check In.[ ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPlRydWU8L0lEPjxFTEM%2bRmFsc2U8L0VMQz48QU1QPkZhbHNlPC9BTVA%2bPFNPSFJJUj5GYWxzZTwvU09IUklSPjxTSFJQPkZhbHNlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7TEFCX1BMLTMwMFQwMDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtLb3JlYW4gKEtvcmVhKTwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0VxdWFsOwlodHRwczovL2dpdGh1Yi5jb20vTWljcm9zb2Z0TGVhcm5pbmcvUEwtMzAwLU1pY3Jvc29mdC1Qb3dlci1CSS1EYXRhLUFuYWx5c3QvYmxvYi9NYWluL0luc3RydWN0aW9ucy8wMS1wcmVwYXJlLWRhdGEtd2l0aC1wb3dlci1xdWVyeS1pbi1wb3dlci1iaS1kZXNrdG9wLm1kLm1hbmlmZXN0LnhtbDwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b)

**Comment by tumultuous1** [comment]
Will the images be added to this repository?  Can I get an ETA please?

**Comment by chriscarty00** [comment]
Files are now located at https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr/tree/OLPRODLOC/Instructions/Linked_image_Files
This can be closed
