### ISSUE TITLE
[Breaking] 02-load-data-with-power-query-in-power-bi-desktop.md

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr#31]
On the English version of Task 6, we have a step that applies filter to **SalesTerritoryAlternateKey** column, which removes a row from the table.

![image](https://user-images.githubusercontent.com/46511987/222942015-71b903a5-bcb4-404f-89ec-c39180b03c3e.png)

However, this step is missing on the Korean version. According to step 5 of the Korean instruction, it states we need to have 10 rows by the end of this Task 6. But due to the missing instruction, we are getting 11 rows at the end of Task 6. It can cause confusion among learners. 

![image](https://user-images.githubusercontent.com/46511987/222942091-4ca2256d-7bb7-499f-98d3-4dbbea8a65d9.png)

We need to add an additional step such as shown below, between step 2 and step 3.

----------
**SalesTerritoryAlternateKey** 열에 필터를 적용하여 0 값을 제거 합니다. 

_이것을 통해서 하나의 행이 제거 됩니다._

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Latest ](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7MDItbG9hZC1kYXRhLXdpdGgtcG93ZXItcXVlcnktaW4tcG93ZXItYmktZGVza3RvcC5tZCA8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7S29yZWFuIChLb3JlYSk8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d) version of the locfile is at PHO 
PM followup needed

**Comment by chriscarty00** [comment]
Files are now in sync - line has been added
