### ISSUE TITLE
[Grammar error] 01-prepare-data-with-power-query-in-power-bi-desktop.md

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr#83]
Need to fix grammatical error. 

Task: [SQL Server 데이터 가져오기](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr/blob/main/Instructions/01-prepare-data-with-power-query-in-power-bi-desktop.md#sql-server-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0)
Step: 8

Current: 
Power Query 편집기 열리는 데이터 변환을 클릭하여 이 작업을 완료합니다.

To be: 
Power Query 편집기가 열리는 데이터 변환을 클릭하여 이 작업을 완료합니다.

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ko-kr/assets/46511987/01f50064-0f29-4202-a299-239d6610c51a)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfile updated](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPkZhbHNlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0VxdWFsOzUwNTgwLkluc3RydWN0aW9ucy5MYWJzLjAxLXByZXBhcmUtZGF0YS13aXRoLXBvd2VyLXF1ZXJ5LWluLXBvd2VyLWJpLWRlc2t0b3AubWQ8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7S29yZWFuIChLb3JlYSk8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)

**Comment by chriscarty00** [comment]
Locfile has published according to lens
